// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmRu2njEE4Tqo3_JvU1AgzyK2oNccm4oo',
    appId: '1:1041354935724:web:f5a3c505ef0cc98193be09',
    messagingSenderId: '1041354935724',
    projectId: 'who-is-the-killer-ai',
    authDomain: 'who-is-the-killer-ai.firebaseapp.com',
    storageBucket: 'who-is-the-killer-ai.firebasestorage.app',
    measurementId: 'G-BFKX5XP45G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJP3ZmChDAR0520eHdKUgTPFzPzRJOSpQ',
    appId: '1:1041354935724:android:4a9a3f1f9b9420e693be09',
    messagingSenderId: '1041354935724',
    projectId: 'who-is-the-killer-ai',
    storageBucket: 'who-is-the-killer-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3juo-siajNDU7Clq7nS0DxZ7aBBkZFR4',
    appId: '1:1041354935724:ios:c904a4185663b22993be09',
    messagingSenderId: '1041354935724',
    projectId: 'who-is-the-killer-ai',
    storageBucket: 'who-is-the-killer-ai.firebasestorage.app',
    iosBundleId: 'com.laplaceapps.whoIsTheKillerAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3juo-siajNDU7Clq7nS0DxZ7aBBkZFR4',
    appId: '1:1041354935724:ios:c904a4185663b22993be09',
    messagingSenderId: '1041354935724',
    projectId: 'who-is-the-killer-ai',
    storageBucket: 'who-is-the-killer-ai.firebasestorage.app',
    iosBundleId: 'com.laplaceapps.whoIsTheKillerAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmRu2njEE4Tqo3_JvU1AgzyK2oNccm4oo',
    appId: '1:1041354935724:web:aa28d171279211e493be09',
    messagingSenderId: '1041354935724',
    projectId: 'who-is-the-killer-ai',
    authDomain: 'who-is-the-killer-ai.firebaseapp.com',
    storageBucket: 'who-is-the-killer-ai.firebasestorage.app',
    measurementId: 'G-FBB0R8X5HX',
  );
}
